
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/springboot/application.properties to edit this template
spring.application.name=SchoolmanagementSystem
spring.datasource.url=jdbc:postgresql://pg-12b69bc0-school.b.aivencloud.com:21747/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_O_2MpKokkpPFOl-H1cR
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080