
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/springboot/application.properties to edit this template
spring.application.name=SchoolmanagementSystem
spring.datasource.url=jdbc:postgresql://dpg-d6pusdvgi27c73bhhip0-a.oregon-postgres.render.com/schooldb_t42y?sslmode=require
spring.datasource.username=schooldb_t42y_user
spring.datasource.password=gsTldQsmO2kMFcEvzcDBorFdgi5vPMnG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080